version: "3.4"
services:
  redis:
    image: redis:7.0.4-bullseye
    container_name: redis-server
    env_file:
      - server/.env
    entrypoint: redis-server
    ports: 
      - 6379:6379
    volumes:
      - redis_data:/data
  node-server:
    container_name: node-server
    build: server/
    ports:
      - 4000:4000
    depends_on:
      - redis-server
  react-client:
    container_name: react-client
    build: client/
    ports:
      - 3000:3000 
    depends_on:
      - node-server
volumes:
  redis_data:
